[package]
name = "azterisk_render"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
dot_vox = "5.2.0"
fontdue = "0.9.4"
glam = "0.33.7"
image = "0.25.10"
pollster = "1.0.1"
rodio = "0.22.2"
thiserror = "2.0.20"
tobj = "4.0.5"
ufbx = "0.11.3"
wgpu = "30.0.1"
winit = "0.30.13"
